
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=video_transcriber
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  web:
    build: .
    command: uvicorn api:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db:
    driver: local